steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/clc-work/app:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/clc-work/app:$SHORT_SHA', 'gcr.io/clc-work/app:latest']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/clc-work/app:$SHORT_SHA', 'clcproject/app:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push clcproject/app:$SHORT_SHA']
images: ['gcr.io/clc-work/app:$SHORT_SHA', 'gcr.io/clc-work/app:latest']
availableSecrets:
  secretManager:
  - versionName: projects/clc-work/secrets/docker-password/versions/1
    env: 'PASSWORD'
  - versionName: projects/clc-work/secrets/docker-username/versions/1
    env: 'USERNAME'
