steps:
- name: python:3.8
  args: [ "python","-m","unittest","discover","--verbose","-s","./add_vals/","-p","test_*.py" ]
  id: unittest
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/clc-work/app:$SHORT_SHA', '.']
  id: build-image
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']
  id: docker-login
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/clc-work/app:$SHORT_SHA', 'clcproject/app:$SHORT_SHA']
  id: tag-docker-image
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push clcproject/app:$SHORT_SHA']
  id: push-image
images: ['gcr.io/clc-work/app:$SHORT_SHA']
availableSecrets:
  secretManager:
  - versionName: projects/clc-work/secrets/docker-password/versions/1
    env: 'PASSWORD'
  - versionName: projects/clc-work/secrets/docker-username/versions/1
    env: 'USERNAME'
